#  server.port=8080
#    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#    spring.datasource.url=jdbc:mysql://localhost:3306/self
#    spring.datasource.username=root
#    spring.datasource.password=12345678
#
#    spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
#
#    spring.jpa.hibernate.ddl-auto=update
#    spring.jpa.properties.hibernate.format_sql=true
#    spring.jpa.show-sql=true
#
#    spring.security.user.name=admin
#    spring.security.user.password=1234
#    spring.security.user.roles=admin
#
#    logging.level.root=info
#    spring.rabbitmq.host=localhost
#    spring.rabbitmq.username=guest
#    spring.rabbitmq.password=guest
#
#    spring.redis.host=localhost
#    spring.redis.port=6379

server:
  port: 8080
  tomcat:
    max-http-form-post-size: 25MB
  error:
    include-stacktrace: ON_PARAM

spring:
  servlet:
    max-file-size: 20MB
    max-request-size: 25MB
  datasource:
      url: jdbc:h2:tcp://localhost/~/mate
      username: sa
      password:
      driver-class-name: org.h2.Driver

  cache:
    type: REDIS

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        show_sql: true
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

# password is echo 'mate-carpool' | base64
jwt:
  secret: bWF0ZS1jYXJwb29sLWp3dC10b2tlbi1zaWduLWtleS1lbHNlLWNlcnQtcDEyLWFhYWFiZGV3cmZkc2Zkc3JlZHNzZHNhCg==

springdoc:
  swagger-ui.path: /api-docs
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

defaultImage: /image/profiles/default.png