#  server.port=8080
#    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#    spring.datasource.url=jdbc:mysql://localhost:3306/self
#    spring.datasource.username=root
#    spring.datasource.password=12345678
#
#    spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
#
#    spring.jpa.hibernate.ddl-auto=update
#    spring.jpa.properties.hibernate.format_sql=true
#    spring.jpa.show-sql=true
#
#    spring.security.user.name=admin
#    spring.security.user.password=1234
#    spring.security.user.roles=admin
#
#    logging.level.root=info
#    spring.rabbitmq.host=localhost
#    spring.rabbitmq.username=guest
#    spring.rabbitmq.password=guest
#
#    spring.redis.host=localhost
#    spring.redis.port=6379

server:
  port: 8080
  tomcat:
    max-http-form-post-size: 25MB

spring:
  servlet:
    max-file-size: 20MB
    max-request-size: 25MB
  datasource:
 #   driver-class-name: com.mysql.cj.jdbc.Driver
 #   url: jdbc:mysql://localhost:3306/mate
 #   username: root
 #   password: 12345678
      url: jdbc:mariadb://localhost:3306/mydb
      username: kunilAWS
      password: sp6356
      driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging.level:
  org.hibernate.SQL: debug
